LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := MusicPlayer
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := retro-music-player-3-2-120-0708.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRODUCT_MODULE := true
LOCAL_DEX_PREOPT := true
include $(BUILD_PREBUILT)
